development:
  adapter: postgresql
  encoding: unicode
  database: ohio_parser_development
  pool: 5
  username: ohio_parser
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: ohio_parser_test
  pool: 5
  username: ohio_parser
  password: